---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True
  vars:
    __verify_pkgconf_by_os_family:
      Debian: '/etc/apt/sources.list.d/haproxy.sources'
      OpenBSD: '/etc/installurl'

    __verify_content_by_os_family:
      Debian: 'http://haproxy.debian.net/'
      OpenBSD: 'https://ftp.fr.openbsd.org/pub/OpenBSD'

  tasks:
    - name: 'Check the packages are installed'
      package:
        name: 'haproxy'
      register: __verify_pkg
      failed_when: __verify_pkg.changed

    - name: 'Get the content of the source file'
      slurp:
        path: "{{ __verify_pkgconf_by_os_family[ ansible_facts['os_family'] ] }}"
      register: __verify_slurp
      failed_when: not __verify_slurp.content | b64decode | regex_search(__verify_content_by_os_family[ ansible_facts['os_family'] ])
