---

- name: 'add/remove apt url-key'
  apt_key:
    url: "{{ item.url }}"
    state: "{% if item.state | default('present') == 'present' %}present{% else %}absent{% endif %}"
  loop: "{{ pkg_config_apt_key_urls }}"
  notify:
    - 'pkg_config_apt_update_cache_handler'

- name: 'add/remove apt id-key'
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
    state: "{% if item.state | default('present') == 'present' %}present{% else %}absent{% endif %}"
  loop: "{{ pkg_config_apt_key_servers }}"
  notify:
    - 'pkg_config_apt_update_cache_handler'
